assets/css/styles.css
assets/js/modal.js
assets/js/pokemon.js
index.html

This iterates through the array and uses pokemon names to get data from the api, which is displayed on the cards. The cards refresh every time a new pokemon is added via the modal

get data to display on cards

---

assets/css/styles.css
assets/js/pokemon.js
index.html

Set the width of the add button, gave it add pokemon label. Edited the fetchPokeImg function so the name would be capitalized even if the input was not

edited add button and capitalize pokemon name

---

assets/js/pokemon.js
assets/js/volume.js
index.html

moved audio to separate file.
added volume slider.

add volume slider

---

assets/js/pokemon.js

added remove function.
added line of code to itterateArray() to check for updated local storage value

added remove function to xbutton

---

assets/js/chuck.js
index.html

added chuck quote api

---

assets/js/musicPlayer.js

added event listener to look for when the audio has "ended", then advance track and loop

added listener to loop music

---

assets/css/chuck.css
assets/js/chuck.js
index.html

added typewriter effect and temp css

added typewriter effect

---

assets/css/styles.css
assets/js/pokemon.js
assets/js/volume.js
index.html

major code update. no longer using the card format. 
the images will be placed around the campfire.
local storage is no longer an array.  instead it is the 4 seat values

changed code to work with the campfire

---

assets/css/styles.css
index.html

I didn't remove it yet incase we still need it, but I commented out the unused CSS to make clean up easier later

commented out unused css

---

assets/js/chuck.js
assets/js/pokemon.js
assets/js/volume.js
index.html

quote will display when pokemon are clicked

Replace chuck

---

assets/css/styles.css
assets/js/chuck.js
assets/js/drag.js
assets/js/pokemon.js
assets/js/volume.js
index.html

added drag and drop functionality to pokemon.
I had to remove the transform css from slot 0 and 3 and move it to setImage(), it was causing the movement to be reversed when dragging.
i changed the data-audio to data-cry, and added data-seat to the slot divs

added drag and drop

---

assets/js/drag.js
assets/js/pokemon.js
index.html

added a check for empty log, and removed the incoming image

fixed empty log bug

---

.vscode/settings.json
assets/css/styles.css
index.html

Styled the modal including image of the campfire with radio buttons around it. "Add to scene" button also closes the modal

Style modal

---

assets/css/styles.css
index.html

Styled the footer and added creators with links to their GitHub accounts

added github links and styled

---

assets/js/background.js
index.html

added background img toggle
button requires styling

added background toggle

---

assets/js/background.js
assets/js/chuck.js
assets/js/pokemon.js

moved the transform css to the setImage()
added if statements for the backgrounds to set either front or back img

adjusted the images and directions based on bg-img

---

assets/js/drag.js
assets/js/pokemon.js
index.html

added pokeball to return/remove pokes
made radio buttons, bigger buttons
clear form between selections

added pokeball and styled radio modal

---

assets/css/styles.css
assets/js/drag.js
index.html

fixed remove

---

assets/js/divs-wiggle-background.js
assets/js/drag.js

hide the original img on drag.

fixed clone bug

---

assets/js/divs-wiggle-background.js
assets/js/drag.js

counter rotate the div during drag

counter rotate the div during drag
